data_file_path: data/simulation_data.json
detection_distance: 2
grid_height: 8
grid_width: 8
hider_action_selection_strategy: EpsilonGreedy
hider_default_q_value: 5
hider_discount_factor: 0.9
hider_from_pretrained: true
hider_initial_epsilon: 0
hider_learning_algorithm: QLearning
hider_learning_rate: 0
hider_min_epsilon: 0
hider_n_steps: 5
hider_pretrained_file_name: data/q_values_hider_big.json
hider_reward: DurationReward
hider_saving_file_path: data/q_values_hider.json
hider_state: CompleteKnowledgeState
max_steps: 20
seed: 42
seeker_action_selection_strategy: DecayEpsilonGreedy
seeker_default_q_value: 5
seeker_discount_factor: 0.9
seeker_from_pretrained: false
seeker_initial_epsilon: 1
seeker_learning_algorithm: QLearning
seeker_learning_rate: 0.1
seeker_min_epsilon: 0
seeker_n_steps: 5
seeker_pretrained_file_name: data/q_values_seeker.json
seeker_reward: WinLoseReward
seeker_saving_file_path: data/q_values_seeker.json
seeker_state: CompleteKnowledgeState
step_delay: 0.1
terminal_delay: 5
total_episodes: 5000
visualize: false
walls:
- - 1
  - 2
- - 2
  - 1
- - 0
  - 2
- - 2
  - 2
- - 4
  - 3
- - 5
  - 3
- - 6
  - 3
- - 4
  - 4
- - 4
  - 5
- - 4
  - 6
- - 4
  - 7
