# Board configuration
grid_width: 7
grid_height: 7

walls:
  - [2, 1]
  - [2, 2]
  - [2, 3]
  - [1, 4]
  - [2, 4]
  - [3, 4]
  # - [5, 7]
  # - [5, 8]
  # - [6, 7]
  # - [7, 1]
  # - [7, 2]
  # - [7, 3]
  # - [7, 4]
  # - [7, 7]
  # - [8, 4]
  # - [8, 4]
  # - [9, 4]


# Game configuration
detection_distance: 1
max_steps: 30
total_episodes: 1_000_000